-- Portable across H2 (MODE=PostgreSQL) and PostgreSQL.

CREATE TABLE IF NOT EXISTS account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number  VARCHAR(12)    NOT NULL UNIQUE,
    owner_name      VARCHAR(100)   NOT NULL,
    account_type    VARCHAR(20)    NOT NULL,
    currency        VARCHAR(3)     NOT NULL,
    balance         NUMERIC(19, 2) NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    version         BIGINT         NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_account_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS transfer (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference        VARCHAR(36)    NOT NULL UNIQUE,
    idempotency_key  VARCHAR(100)   UNIQUE,
    from_account_id  BIGINT         REFERENCES account (id),
    to_account_id    BIGINT         REFERENCES account (id),
    amount           NUMERIC(19, 2) NOT NULL,
    description      VARCHAR(140),
    status           VARCHAR(20)    NOT NULL,
    failure_reason   VARCHAR(40),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ledger_entry (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT         NOT NULL REFERENCES account (id),
    transfer_id    BIGINT         REFERENCES transfer (id),
    entry_type     VARCHAR(10)    NOT NULL,
    amount         NUMERIC(19, 2) NOT NULL,
    balance_after  NUMERIC(19, 2) NOT NULL,
    description    VARCHAR(140),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_ledger_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS ix_ledger_account ON ledger_entry (account_id);
CREATE INDEX IF NOT EXISTS ix_ledger_transfer ON ledger_entry (transfer_id);
